### ISSUE TITLE
Duplicate link

### ISSUE THREAD

**Issue by azeno** [gregsn/MergeVLDocs#6]
Just seen this after a merge:
![image](https://user-images.githubusercontent.com/573618/106888948-92b8df80-66e7-11eb-9a9f-df3e4ae5d4b8.png)

**Comment by gregsn** [comment]
please leave a detailed description of how to reproduce. It's fine if you refer to commits in a private repo that I have access to.

**Comment by gregsn** [comment]
ebab31cd71e7e21299025b12271699bf9a05ff43
